# Resources:
# + https://aka.ms/yaml
# tutorial: 
# + https://medium.com/@muppedaanvesh/%EF%B8%8F-azure-devops-pipeline-essentials-jobs-stages-tasks-steps-%EF%B8%8F-1757d6366201
# + https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops
trigger:
    - dev

pool:
    vmImage: ubuntu-latest


stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UseNode@1
            inputs:
              version: "16.x"
            displayName: "Install Node.js"

          - script: |
              npm install
            displayName: "npm install"

          - script: |
              npm run lint:check
            displayName: "npm lint:check"

          - script: |
              npm run format:check
            displayName: "npm format:check"

          - script: |
              npm run build
            displayName: "npm build"

#          - script: |
#              npm run test
#            displayName: "npm test"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
            displayName: "Archive build output"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
            displayName: "Publish Artifact"
  - stage: Deploy
    jobs:
      - job: DeployJob
        steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure for Students(afcb3461-de74-49a5-aa96-4fb6c265710e)'
            appType: 'webAppLinux'
            WebAppName: 'gambler-pawns-back'
            deployToSlotOrASE: true
            ResourceGroupName: 'gambler-pawns-back_group'
            SlotName: 'production'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
            RuntimeStack: 'NODE|18-lts'
            StartupCommand: 'npm run start:prod'